# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/crepp052/files_pyqt/tuto_pyqt_pyserial_fichier_filedialog_textedit_gcode/tuto_pyqt_pyserial_fichier_filedialog_textedit_gcode.ui'
#
# Created: Sat Mar 28 21:43:01 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(638, 455)
        self.lineEditChemin = QtGui.QLineEdit(Form)
        self.lineEditChemin.setGeometry(QtCore.QRect(195, 125, 436, 21))
        self.lineEditChemin.setObjectName(_fromUtf8("lineEditChemin"))
        self.textEdit = QtGui.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(195, 185, 431, 261))
        self.textEdit.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.pushButtonNouveau = QtGui.QPushButton(Form)
        self.pushButtonNouveau.setGeometry(QtCore.QRect(195, 155, 86, 21))
        self.pushButtonNouveau.setObjectName(_fromUtf8("pushButtonNouveau"))
        self.pushButtonOuvrir = QtGui.QPushButton(Form)
        self.pushButtonOuvrir.setGeometry(QtCore.QRect(285, 155, 85, 21))
        self.pushButtonOuvrir.setObjectName(_fromUtf8("pushButtonOuvrir"))
        self.pushButtonEnregistrer = QtGui.QPushButton(Form)
        self.pushButtonEnregistrer.setGeometry(QtCore.QRect(375, 155, 86, 21))
        self.pushButtonEnregistrer.setObjectName(_fromUtf8("pushButtonEnregistrer"))
        self.pushButtonEnvoiGCode = QtGui.QPushButton(Form)
        self.pushButtonEnvoiGCode.setGeometry(QtCore.QRect(470, 155, 136, 21))
        self.pushButtonEnvoiGCode.setObjectName(_fromUtf8("pushButtonEnvoiGCode"))
        self.line_5 = QtGui.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(190, 110, 436, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.labelTraceAnalyseChaine = QtGui.QLabel(Form)
        self.labelTraceAnalyseChaine.setGeometry(QtCore.QRect(200, 5, 276, 16))
        self.labelTraceAnalyseChaine.setObjectName(_fromUtf8("labelTraceAnalyseChaine"))
        self.textEditTraceAnalyseChaine = QtGui.QTextEdit(Form)
        self.textEditTraceAnalyseChaine.setGeometry(QtCore.QRect(200, 20, 426, 91))
        self.textEditTraceAnalyseChaine.setStyleSheet(_fromUtf8("color: rgb(0, 170, 0);\n"
"background-color: rgb(188, 255, 193);\n"
""))
        self.textEditTraceAnalyseChaine.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEditTraceAnalyseChaine.setObjectName(_fromUtf8("textEditTraceAnalyseChaine"))
        self.labelTraceEnvoiSerie = QtGui.QLabel(Form)
        self.labelTraceEnvoiSerie.setGeometry(QtCore.QRect(5, 200, 191, 16))
        self.labelTraceEnvoiSerie.setObjectName(_fromUtf8("labelTraceEnvoiSerie"))
        self.labelFinLigne = QtGui.QLabel(Form)
        self.labelFinLigne.setGeometry(QtCore.QRect(5, 155, 71, 16))
        self.labelFinLigne.setObjectName(_fromUtf8("labelFinLigne"))
        self.comboBoxDebit = QtGui.QComboBox(Form)
        self.comboBoxDebit.setGeometry(QtCore.QRect(5, 60, 121, 24))
        self.comboBoxDebit.setObjectName(_fromUtf8("comboBoxDebit"))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.comboBoxDebit.addItem(_fromUtf8(""))
        self.textEditReception = QtGui.QTextEdit(Form)
        self.textEditReception.setGeometry(QtCore.QRect(5, 340, 171, 111))
        self.textEditReception.setStyleSheet(_fromUtf8("background-color: rgb(244, 255, 190);"))
        self.textEditReception.setObjectName(_fromUtf8("textEditReception"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(5, 190, 166, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.comboBoxFinLigne = QtGui.QComboBox(Form)
        self.comboBoxFinLigne.setGeometry(QtCore.QRect(5, 170, 121, 24))
        self.comboBoxFinLigne.setObjectName(_fromUtf8("comboBoxFinLigne"))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.comboBoxFinLigne.addItem(_fromUtf8(""))
        self.pushButtonEnvoi = QtGui.QPushButton(Form)
        self.pushButtonEnvoi.setGeometry(QtCore.QRect(130, 155, 41, 41))
        self.pushButtonEnvoi.setObjectName(_fromUtf8("pushButtonEnvoi"))
        self.spinBoxDelaiReception = QtGui.QSpinBox(Form)
        self.spinBoxDelaiReception.setGeometry(QtCore.QRect(110, 85, 71, 23))
        self.spinBoxDelaiReception.setMaximum(10000)
        self.spinBoxDelaiReception.setProperty("value", 20)
        self.spinBoxDelaiReception.setObjectName(_fromUtf8("spinBoxDelaiReception"))
        self.comboBoxPort = QtGui.QComboBox(Form)
        self.comboBoxPort.setGeometry(QtCore.QRect(5, 20, 121, 24))
        self.comboBoxPort.setEditable(True)
        self.comboBoxPort.setObjectName(_fromUtf8("comboBoxPort"))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.comboBoxPort.addItem(_fromUtf8(""))
        self.labelDebit = QtGui.QLabel(Form)
        self.labelDebit.setGeometry(QtCore.QRect(5, 45, 111, 16))
        self.labelDebit.setObjectName(_fromUtf8("labelDebit"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(175, 10, 16, 441))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.textEditTraceEnvoiSerie = QtGui.QTextEdit(Form)
        self.textEditTraceEnvoiSerie.setGeometry(QtCore.QRect(5, 215, 171, 106))
        self.textEditTraceEnvoiSerie.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(170, 255, 255);"))
        self.textEditTraceEnvoiSerie.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEditTraceEnvoiSerie.setObjectName(_fromUtf8("textEditTraceEnvoiSerie"))
        self.pushButtonInitSerial = QtGui.QPushButton(Form)
        self.pushButtonInitSerial.setGeometry(QtCore.QRect(130, 5, 41, 41))
        self.pushButtonInitSerial.setObjectName(_fromUtf8("pushButtonInitSerial"))
        self.labelChaineEnvoi = QtGui.QLabel(Form)
        self.labelChaineEnvoi.setGeometry(QtCore.QRect(5, 115, 121, 16))
        self.labelChaineEnvoi.setObjectName(_fromUtf8("labelChaineEnvoi"))
        self.labelReception = QtGui.QLabel(Form)
        self.labelReception.setGeometry(QtCore.QRect(5, 325, 171, 16))
        self.labelReception.setObjectName(_fromUtf8("labelReception"))
        self.labelDelaiRecept = QtGui.QLabel(Form)
        self.labelDelaiRecept.setGeometry(QtCore.QRect(5, 90, 106, 16))
        self.labelDelaiRecept.setObjectName(_fromUtf8("labelDelaiRecept"))
        self.lineEditChaineEnvoi = QtGui.QLineEdit(Form)
        self.lineEditChaineEnvoi.setGeometry(QtCore.QRect(5, 130, 166, 23))
        self.lineEditChaineEnvoi.setText(_fromUtf8(""))
        self.lineEditChaineEnvoi.setObjectName(_fromUtf8("lineEditChaineEnvoi"))
        self.pushButtonStop = QtGui.QPushButton(Form)
        self.pushButtonStop.setGeometry(QtCore.QRect(130, 50, 41, 31))
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(5, 105, 166, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.labelPort = QtGui.QLabel(Form)
        self.labelPort.setGeometry(QtCore.QRect(5, 5, 101, 16))
        self.labelPort.setObjectName(_fromUtf8("labelPort"))

        self.retranslateUi(Form)
        self.comboBoxFinLigne.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "PyQt : Fichiers : Ajouter données dans un fichier ", None))
        self.pushButtonNouveau.setText(_translate("Form", "Nouveau", None))
        self.pushButtonOuvrir.setText(_translate("Form", "Ouvrir", None))
        self.pushButtonEnregistrer.setText(_translate("Form", "Enregistrer", None))
        self.pushButtonEnvoiGCode.setText(_translate("Form", "Envoyer GCode", None))
        self.labelTraceAnalyseChaine.setText(_translate("Form", "Analyse de la chaine recue sur port série : ", None))
        self.labelTraceEnvoiSerie.setText(_translate("Form", "Envoi sur le port série : ", None))
        self.labelFinLigne.setText(_translate("Form", "Fin de ligne :", None))
        self.comboBoxDebit.setItemText(0, _translate("Form", "115200", None))
        self.comboBoxDebit.setItemText(1, _translate("Form", "57600", None))
        self.comboBoxDebit.setItemText(2, _translate("Form", "38400", None))
        self.comboBoxDebit.setItemText(3, _translate("Form", "28800", None))
        self.comboBoxDebit.setItemText(4, _translate("Form", "19200", None))
        self.comboBoxDebit.setItemText(5, _translate("Form", "14400", None))
        self.comboBoxDebit.setItemText(6, _translate("Form", "9600", None))
        self.comboBoxDebit.setItemText(7, _translate("Form", "4800", None))
        self.comboBoxFinLigne.setItemText(0, _translate("Form", "Rien", None))
        self.comboBoxFinLigne.setItemText(1, _translate("Form", "Saut de ligne (\\n = LF)", None))
        self.comboBoxFinLigne.setItemText(2, _translate("Form", "Retour Chariot (\\r = CR)", None))
        self.comboBoxFinLigne.setItemText(3, _translate("Form", "Les 2 (LF + CR)", None))
        self.pushButtonEnvoi.setText(_translate("Form", "Envoi", None))
        self.comboBoxPort.setItemText(0, _translate("Form", "/dev/ttyACM0", None))
        self.comboBoxPort.setItemText(1, _translate("Form", "/dev/ttyACM1", None))
        self.comboBoxPort.setItemText(2, _translate("Form", "/dev/ttyUSB0", None))
        self.comboBoxPort.setItemText(3, _translate("Form", "/dev/ttyUSB1", None))
        self.labelDebit.setText(_translate("Form", "Débit Série (bauds) :", None))
        self.pushButtonInitSerial.setText(_translate("Form", "Init", None))
        self.labelChaineEnvoi.setText(_translate("Form", "Chaîne à envoyer :", None))
        self.labelReception.setText(_translate("Form", "Réception sur le port série : ", None))
        self.labelDelaiRecept.setText(_translate("Form", "Délai Récept. (ms)", None))
        self.pushButtonStop.setText(_translate("Form", "Stop", None))
        self.labelPort.setText(_translate("Form", "Port Série :", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

